//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_permissions_profile
    {
        public int prof_id { get; set; }
        public string prof_name { get; set; }
        public int C_sort { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    }
}
