//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public long id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public int C_sort { get; set; }
        public string topic { get; set; }
        public long parent_id { get; set; }
        public string background_color { get; set; }
        public int body_sort { get; set; }
    }
}
