//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_image
    {
        public int id { get; set; }
        public string image { get; set; }
        public int product_id { get; set; }
        public int C_sort { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
    }
}
