//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide_image
    {
        public int id { get; set; }
        public string image { get; set; }
        public int C_sort { get; set; }
        public int slider_num { get; set; }
        public string title1 { get; set; }
        public string title2 { get; set; }
    }
}
