//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        public long id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string ip { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime active { get; set; }
    }
}
