//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_page
    {
        public int ap_id { get; set; }
        public string ap_name { get; set; }
        public string ap_fa_icon { get; set; }
        public string ap_view_slug { get; set; }
        public string ap_view_link { get; set; }
        public string ap_add_slug { get; set; }
        public string ap_add_link { get; set; }
        public string ap_edit_slug { get; set; }
        public string ap_edit_link { get; set; }
        public string ap_delete_slug { get; set; }
        public string ap_delete_link { get; set; }
        public int C_sort { get; set; }
        public int C_parent_id { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    }
}
