//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_permissions
    {
        public int perm_id { get; set; }
        public int perm_profile { get; set; }
        public int perm_page { get; set; }
        public int perm_view { get; set; }
        public int perm_add { get; set; }
        public int perm_edit { get; set; }
        public int perm_delete { get; set; }
        public int perm_all { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    }
}
