//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard
    {
        public int id { get; set; }
        public string about { get; set; }
        public string customer { get; set; }
        public string return_policy { get; set; }
        public string how { get; set; }
        public string faq { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string background { get; set; }
        public string header { get; set; }
        public string logo { get; set; }
    }
}
