//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eAdminDBEntities : DbContext
    {
        public eAdminDBEntities()
            : base("name=eAdminDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_ci_sessions> admin_ci_sessions { get; set; }
        public virtual DbSet<admin_page> admin_page { get; set; }
        public virtual DbSet<admin_permissions> admin_permissions { get; set; }
        public virtual DbSet<admin_permissions_profile> admin_permissions_profile { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<banner> banners { get; set; }
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<ci_sessions> ci_sessions { get; set; }
        public virtual DbSet<ct> cts { get; set; }
        public virtual DbSet<dashboard> dashboards { get; set; }
        public virtual DbSet<fa_icon> fa_icon { get; set; }
        public virtual DbSet<order_list> order_list { get; set; }
        public virtual DbSet<order_num> order_num { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<product_image> product_image { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<slide_image> slide_image { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visitor> visitors { get; set; }
        public virtual DbSet<MSSsmaDmNCKeyColumn> MSSsmaDmNCKeyColumns { get; set; }
        public virtual DbSet<MSSsmaDmTable> MSSsmaDmTables { get; set; }
    }
}
