//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_num
    {
        public int id { get; set; }
        public int visitor_id { get; set; }
        public string status { get; set; }
        public System.DateTime created { get; set; }
        public string address { get; set; }
        public string ptype { get; set; }
        public string mtype { get; set; }
        public string cnt { get; set; }
        public string ct { get; set; }
        public string area { get; set; }
        public string addr { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string email { get; set; }
        public int total { get; set; }
    }
}
