//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string body { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime pubdate { get; set; }
        public int parent_id { get; set; }
        public string code { get; set; }
        public string review { get; set; }
        public int discount { get; set; }
        public string price { get; set; }
        public int oprice { get; set; }
        public int sale { get; set; }
        public int C_view { get; set; }
        public int C_bought { get; set; }
        public int publisher { get; set; }
        public int sales_type { get; set; }
        public int C_status { get; set; }
        public int quantity { get; set; }
    }
}
